### ISSUE TITLE
Checksum algorithm

### ISSUE THREAD

**Issue by 0xSombra** [willkirkby/overwatch-highlights#4]
They're using HMAC-SHA256.
```csharp
using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;

byte[] Key =
{
	0x0C, 0x1A, 0xAB, 0xE8, 0xCC, 0xBF, 0x85, 0xBB, 0x77, 0x7B, 0xE2, 0xD0, 0xCB, 0x68, 0xD7, 0x35,
	0x75, 0x7C, 0x2F, 0x3A, 0x32, 0x96, 0xA4, 0x98, 0x57, 0x0F, 0xB3, 0x54, 0x56, 0x2F, 0xD5, 0x1C
};
using (var sha256 = new HMACSHA256(Key))
{
	using (var fs = File.OpenRead("path/to/highlight.file"))
	{
		fs.Seek(40, SeekOrigin.Begin); // Right after the file size
		var digest = sha256.ComputeHash(fs);
		Console.WriteLine(digest.Aggregate("", (s, b) => $"{s}{b:X2}"));
	}
}
```

**Comment by lunasorcery** [comment]
I'm not even gonna ask how you begin to figure something like that out. What's the legality of including that key in my source?

**Comment by 0xSombra** [comment]
I don't know. @naomichan has been using crypto stuff that I extracted from the client and blizzard doesn't seem to mind.
As long as you're not emulating overwatch servers or making hacks, I don't think they would care.

**Comment by neptuwunium** [comment]
Not any less legal than reverse engineering the file format to begin with.

As long as you don't implement something that can modify highlights, it should be fine with Blizzard.

Blizzard really only goes after things that harm their property, such as hacks and private servers/emulators.

They'll more than likely start to randomize it with each patch like they did with CMF encryption.
